# Generated by Django 2.2.5 on 2019-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0012_auto_20190819_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.TextField(),
        ),
    ]
