# Generated by Django 3.0.3 on 2020-03-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0013_auto_20190922_1834'),
        ('YtManagerApp', 'video_duration'),
        ('YtManagerApp', 'subscription_last_synchronised'),
    ]

    operations = [
    ]
