# Generated by Django 3.0.3 on 2021-03-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0014_merge_20200302_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='provider',
            field=models.CharField(default='Youtube', max_length=64),
            preserve_default=False,
        ),
    ]
