# Generated by Django 3.0.3 on 2021-03-24 22:41

from django.conf import settings
from django.core.files import File
from django.db import migrations, models
from typing import TYPE_CHECKING
import os.path

if TYPE_CHECKING:
    from YtManagerApp.models import Subscription as SubscriptionModel
    from YtManagerApp.models import Video as VideoModel


def create_subscription_images(apps, schema_editor):
    Subscription: SubscriptionModel = apps.get_model('YtManagerApp', 'Subscription')
    for subscription in Subscription.objects.all():
        f = open(os.path.join(settings.MEDIA_ROOT, subscription.thumbnail.replace(settings.MEDIA_URL, "")))
        myimage = File(f)
        subscription.thumb.save("", myimage)
        subscription.save()

def create_video_images(apps, schema_editor):
    Video: VideoModel = apps.get_model('YtManagerApp', 'Video')
    for video in Video.objects.all():
        f = open(os.path.join(settings.MEDIA_ROOT, video.thumbnail.replace(settings.MEDIA_URL, "")))
        myimage = File(f)
        video.thumb.save("", myimage)
        video.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('YtManagerApp', '0015_subscription_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='thumb',
            field=models.ImageField(null=True, upload_to='thumbnails/sub'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumb',
            field=models.ImageField(null=True, upload_to='thumbnails/video'),
        ),
        migrations.RunPython(create_subscription_images),
        migrations.RunPython(create_video_images)
    ]
